SET SERVEROUTPUT ON
DECLARE
TYPE ABC IS VARRAY(110) OF NUMBER;
V_ABC  ABC;


BEGIN
SELECT EMPLOYEE_ID,SALARY ,FIRST_NAME BULK COLLECT INTO V_ABC,V_XYZ
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (10,20,30);
FOR I IN V_ABC.FIRST..V_ABC.LAST 
LOOP
DBMS_OUTPUT.PUT_LINE(V_ABC.COUNT ||' ' ||V_ABC(I)||' ' ||V_XYZ(I));
END LOOP;
END;
SET SERVEROUTPUT ON
DECLARE
TYPE ABC IS TABLE OF EMPLOYEES%ROWTYPE;
V_ABC  ABC;


BEGIN
SELECT * BULK COLLECT INTO V_ABC
FROM EMPLOYEES;
--WHERE DEPARTMENT_ID IN (10,20,30);
FOR I IN V_ABC.FIRST..V_ABC.LAST 
LOOP
DBMS_OUTPUT.PUT_LINE(V_ABC(I).EMPLOYEE_ID||' ' ||V_ABC(I).FIRST_NAME);
END LOOP;
END;
SET SERVEROUTPUT ON
DECLARE
TYPE ABC IS TABLE OF EMPLOYEES%ROWTYPE INDEX BY PLS_INTEGER;--VARCHAR ; --;BINARY_INTEGER ;--PLS_INTEGER;
V_ABC  ABC;
BEGIN
SELECT * BULK COLLECT INTO V_ABC
FROM EMPLOYEES;
--WHERE DEPARTMENT_ID IN (10,20,30);
FOR I IN V_ABC.FIRST..V_ABC.LAST 
LOOP
DBMS_OUTPUT.PUT_LINE(V_ABC(I).EMPLOYEE_ID||' ' ||V_ABC(I).FIRST_NAME);
END LOOP;
END;


SQL%ROWCOUNT
SET SERVEROUTPUT ON
DECLARE
CURSOR C1 IS
SELECT E.*,D.DEPARTMENT_NAME FROM EMPLOYEES E,DEPARTMENTS D
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID;
TYPE REC IS TABLE OF C1%ROWTYPE;
V_REC REC;
BEGIN
OPEN C1 ;
LOOP
FETCH C1 BULK COLLECT INTO V_REC LIMIT 10;

FOR I IN 1..V_REC.COUNT LOOP
DBMS_OUTPUT.PUT_LINE(V_REC(I).FIRST_NAME);
END LOOP;
EXIT WHEN C1%NOTFOUND;
END LOOP;
CLOSE C1;
END;


SET SERVEROUTPUT ON
DECLARE
CURSOR C1 IS 
SELECT * FROM EMPLOYEES;

TYPE ABC IS TABLE OF C1%ROWTYPE;
V_ABC ABC;

BEGIN
OPEN C1;
LOOP
FETCH C1 BULK COLLECT INTO V_ABC LIMIT 10;

FORALL I IN 1..V_ABC.COUNT 
INSERT INTO BULK_LOAD VALUES(V_ABC(I).EMPLOYEE_ID,V_ABC(I).FIRST_NAME);

DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
EXIT WHEN C1%NOTFOUND;
END LOOP;
CLOSE C1;
END;

SET SERVEROUTPUT ON
DECLARE
CURSOR C1 IS 
SELECT * FROM EMPLOYEES;

TYPE ABC IS TABLE OF C1%ROWTYPE;
V_ABC ABC;

BEGIN
OPEN C1;
LOOP
FETCH C1 BULK COLLECT INTO V_ABC ;

FORALL I IN 1..V_ABC.COUNT 
INSERT INTO BULK_LOAD --VALUES(V_ABC(I).EMPLOYEE_ID,V_ABC(I).FIRST_NAME);
(SELECT V_ABC(I).EMPLOYEE_ID,V_ABC(I).FIRST_NAME
FROM DUAL
WHERE V_ABC(I).EMPLOYEE_ID > 200);
DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
EXIT WHEN C1%NOTFOUND;
END LOOP;
CLOSE C1;
END;

CREATE OR REPLACE TYPE OBJ_NESTED AS OBJECT
(ID NUMBER,
SAL NUMBER);

CREATE OR REPLACE TYPE ARY_NESTED AS TABLE OF OBJ_NESTED;

create or replace PROCEDURE P_FIRST_ARR
(P_ID IN ARY_NESTED)
IS

V_REC ARY_NESTED;

BEGIN
SELECT OBJ_NESTED(EMPLOYEE_ID,SALARY)
BULK COLLECT INTO V_REC
FROM EMPLOYEES E,TABLE(P_ID) P
WHERE
E.EMPLOYEE_ID=P.ID;
FOR I IN 1..V_REC.COUNT 
LOOP
DBMS_OUTPUT.PUT_LINE(V_REC(I).ID||' ' ||V_REC(I).SAL);
END LOOP;
END;

SET SERVEROUTPUT ON
DECLARE
V_ID ARY_NESTED;
BEGIN
V_ID :=ARY_NESTED();
V_ID.EXTEND(2);
V_ID(1):=OBJ_NESTED(100,20000);
--V_ID.EXTEND;
V_ID(2):=OBJ_NESTED(107,30000);
P_FIRST_ARR (P_ID=>V_ID);
END;
