DATA_TYPES:

NUMBER
VARCHAR LIMIT 4000
VARCHAR2 LIMIT 4000 NULL HANDLING
CHAR LIMIT 2000
DATE
CLOB CHARACTER LARGE OBJECT,MORE THAN 4000
BLOB BINARY LARGE OBJECT,IMAGES,AUDIOS,VIDEOS

CHAR(20)
VARCHAR(10)
VARCHAR2(40)

SQL STATEMENTS;
DML - DATA MANIPULATION LANGUAGE
SELECT
INSERT
UPDATE
DELETE
NOTE:MANUAL COMMIT

DDL - DATA DEFINITION LANGUAGE
CREATE
ALTER
ADD
DROP
RENAME
TRUNCATE
NOTE:AUTO COMMIT

TCL - TRNSMISSION/TRANSACTION CONTROL LANGUAGE
COMMIT
ROLLBACK
SAVEPOINT

DCL - DATA CONTROL LANGUAGE
GRANT
REVOKE


CREATE TABLE BATCH30(ID NUMBER,NAME VARCHAR2(50));
SELECT * FROM BATCH30;
DESC BATCH30;
INSERT INTO BATCH30 VALUES(10,'VIGNESH');
COMMIT;
INSERT INTO BATCH30 VALUES(20,'NANDA');
INSERT INTO BATCH30 VALUES(30,'NAVIN');
INSERT INTO BATCH30 VALUES(40,'HARI');
INSERT INTO BATCH30 VALUES(50,'KARTHIK');
INSERT INTO BATCH30 VALUES(60,'VINOTH');
COMMIT;

TABLE NAME= 30 CHARACTERS/BYTES
SCHEMA/USER
UPDATE BATCH30 SET NAME='NANDHA' WHERE ID=20;
SELECT * FROM BATCH30;
COMMIT;
DELETE FROM BATCH30 WHERE ID=60;

SELECT ID FROM BATCH30;
SELECT NAME FROM BATCH30;
SELECT ID,NAME FROM BATCH30;


